ContentDeliverySystem.WEB/Controllers/GenreController.cs
using ContentDeliverySystem.SVC;
using ContentDeliverySystem.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContentDeliverySystem.WEB.Controllers
{
    public class GenreController : Controller
    {
        //
        // GET: /Genre/

        IGenreService genreService;

        public GenreController(IGenreService genreService)
        {
            this.genreService = genreService;
        }

        public ActionResult Index()
        {
            try
            {
                var genres = genreService.GetAll();
                return View(genres);
            }
            catch (InvalidTokenException)
            {
                return RedirectToAction("index", "home");

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Insert()
        {
            ViewBag.Parents = genreService.GetAll();
            return View("insert");
        }

        [HttpPost]
        public ActionResult Create(string name,int? idParent)
        {
            try
            {
                genreService.Create(name, idParent);
                string Message = "Genre Created";
                InternalNotification.Success(Message);
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
            }
            return RedirectToAction("index");
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                var genre = genreService.Find(Id);
                ViewBag.Parents = genreService.GetAll();
                return View(genre);
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
                return RedirectToAction("index");
            }
        }

        public ActionResult Update(DAL.Genres genre, int id)
        {
            try
            {
                genreService.Update(id, genre);
                InternalNotification.Success("Genre updated");
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
            }
            return RedirectToAction("index");
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            try
            {
                var genre = genreService.Find(Id);
                genreService.Delete(genre);
                InternalNotification.Success("Genre Deleted");
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
            }
            return RedirectToAction("index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (disposing)
                genreService.Dispose();
        }

    }
}

ContentDeliverySystem.WEB/Controllers/GroupController.cs
using ContentDeliverySystem.SVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContentDeliverySystem.WEB.Models;

namespace ContentDeliverySystem.WEB.Controllers
{
    public class GroupController : Controller
    {
        //
        // GET: /Group/

        IGroupService GroupService;

        public GroupController(IGroupService Service)
        {
            GroupService = Service;
        }

        public ActionResult Index()
        {
            try
            {
                var Groups = GroupService.GetAll();
                return View(Groups);
            }
            catch (InvalidTokenException)
            {
                return RedirectToAction("index","home");
                
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Insert()
        {
            return View("insert");
        }
        [HttpPost]
        public ActionResult Create(string Name)
        {
            try
            {
                GroupService.Create(Name);
                string Message  = "Group Created";
                InternalNotification.Success(Message);
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
            }
            return RedirectToAction("index");
        }
        
        public ActionResult Edit(int Id)
        {
            try
            {
                var Group = GroupService.Find(Id);
                return View(Group);
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
                return RedirectToAction("index");
            }
        }

        public ActionResult Update(int Id, string Name, bool IsActive=false)
        {
            try
            {
                GroupService.Update(Id, Name, IsActive);
                InternalNotification.Success("Group updated");
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
            }
            return RedirectToAction("index");
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            try
            {
                GroupService.Delete(Id);
                InternalNotification.Success("Group Deleted");
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
            }
            return RedirectToAction("index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (disposing)
                GroupService.Dispose();
        }

    }
}

ContentDeliverySystem.WEB/Controllers/UsersController.cs
using ContentDeliverySystem.SVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContentDeliverySystem.WEB.Models;

namespace ContentDeliverySystem.WEB.Controllers
{
    public class UsersController : Controller
    {

        IUserService UserService;
        IGroupService GroupService;
        public UsersController(IUserService Service, IGroupService GroupService)
        {
            UserService = Service;
            this.GroupService = GroupService;
        }

        public ActionResult Index()
        {
            return View(UserService.GetUsers());
        }

        public ActionResult Active(int ticket)
        {
            try
            {
                UserService.ActivateUser(ticket);
                return View("Activated");
            }
            catch
            {
                return View("ActivationError");
            }
        }

        public ActionResult Insert()
        {
            try
            {
                ViewBag.Groups = GroupService.GetAll().Where(x => x.Active);
                return View();
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex);
                return RedirectToAction("index");
            }
        }

        public ActionResult Edit(int Id)
        {
            ViewBag.Groups = GroupService.GetAll().Where(x => x.Active);
            var User = UserService.Find(Id);
            return View(User);
        }

        public ActionResult ResendActivationEmail(string Email)
        {
            try
            {
                UserService.ResendActiveEmail(Email, GetActiveEndPoint());
                InternalNotification.Success("The email was sent");
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex.Message);
            }
            return RedirectToAction("index");
        }

        public ActionResult Create(string Adress, string Name, DateTime BirthDate, string Cellphone, string CEP, string CPF, string Email, byte? Gender, int IdGroup, string Phone, string Password, string PasswordConfirmation)
        {

            if (Password != PasswordConfirmation)
            {
                InternalNotification.Error("Password does not match");
                RedirectToAction("insert");
            }

            try
            {
                var CreatedId = UserService.Create(new DAL.Users()
                {
                    Name = Name,
                    Adress = Adress,
                    BirthDate = BirthDate,
                    Cellphone = Cellphone,
                    CEP = CEP,
                    CPF = CPF,
                    Email = Email,
                    Gender = Gender,
                    IdGroup = IdGroup,
                    Phone = Phone
                }, Password, GetActiveEndPoint());

                if (CreatedId < 1)
                    throw new Exception("Could not Create User");

                //InternalNotification.Success("User created");
                return RedirectToAction("UserCreated", "Home");
            }
            catch (Exception)
            {
                InternalNotification.Error("Ocorreu um erro inesperado, por favor tente mais tarde");
                return RedirectToAction("insert");
            }
        }

        public ActionResult Update(int Id, string Adress, string Name, DateTime BirthDate, string Cellphone, string CEP, byte? Gender, int IdGroup, string Phone)
        {
            try
            {
                UserService.Update(new DAL.Users()
               {
                   Id = Id,
                   Adress = Adress,
                   Name = Name,
                   BirthDate = BirthDate,
                   Cellphone = Cellphone,
                   CEP = CEP,
                   Gender = Gender,
                   IdGroup = IdGroup,
                   Phone = Phone
               });


                InternalNotification.Success("User updated");
                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex.Message);
                RedirectToAction("insert");
            }
            return RedirectToAction("index");
        }

        public ActionResult Delete(int Id)
        {
            try
            {
                var Deleted = UserService.Delete(Id);
                InternalNotification.Success("User deleted");
            }
            catch (Exception ex)
            {
                InternalNotification.Error(ex.Message);
            }
            return RedirectToAction("index");
        }
        private string GetActiveEndPoint()
        {
            return Url.Action("active", "users",
               routeValues: null,
               protocol: Request.Url.Scheme);
        }
    }
}

ContentDeliverySystem.WEB/Views/Shared/_DeleteModal.cshtml
@{
    Layout = null;
}
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>Are you sure you want to delete this item?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger cds-btn-del-asserted">Yes, Delete</button>
            </div>
        </div>
    </div>
</div>

ContentDeliverySystem.WEB/Views/Shared/_Internal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>CDS - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datatable")
    @Scripts.Render("~/bundles/modernizr")
    
    <link href="@Url.Content("~/Content/toastr.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Layout.css")" rel="stylesheet" />
</head>
<body>
    <div class="wrapper col-xs-offset-1 col-xs-10" style="margin-top:10px">
        @{Html.RenderPartial("_TopMenu");}


        @RenderBody()
    </div>
    @{Html.RenderPartial("_DeleteModal");}
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatable")
    @Scripts.Render("~/bundles/mask")

    <script src="@Url.Content("~/Scripts/toastr.min.js")"></script>
    @Scripts.Render("~/bundles/notification")
    <script src="@Url.Content("~/Scripts/ModalDeleteHelper.js")"></script>
    @{var SystemMessage = ContentDeliverySystem.WEB.Models.InternalNotification.Retrieve();}
    @if (SystemMessage != null)
    {
        <script>
            systemNotifications.send("@(SystemMessage.Message)", "@(SystemMessage.MessageTypeText)");
        </script>
    }



    @RenderSection("scripts", required: false)
</body>
</html>

ContentDeliverySystem.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>CDS - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/toastr.min.css")" rel="stylesheet" />
    

</head>
<body>
    <div class="wrapper col-xs-offset-1 col-xs-10" style="margin-top:10px">
        
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="@Url.Content("~/Scripts/toastr.min.js")"></script>
    @Scripts.Render("~/bundles/notification")
    <script src="@Url.Content("~/Scripts/ModalDeleteHelper.js")"></script>
    @{var SystemMessage = ContentDeliverySystem.WEB.Models.InternalNotification.Retrieve();}
    @if (SystemMessage != null)
    {
        <script>
            systemNotifications.send("@(SystemMessage.Message)", "@(SystemMessage.MessageTypeText)");
        </script>
    }



    @RenderSection("scripts", required: false)
</body>
</html>

ContentDeliverySystem.WEB/Views/Shared/_TopMenu.cshtml
@using ContentDeliverySystem.WEB.Models;
@using ContentDeliverySystem.SVC.DTO;
@{
    Layout = null;
    var SessionObj = Session[GlobalParams.UserSessionKey];
    AuthResponse Auth = (AuthResponse)SessionObj;
}
@if (SessionObj != null)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Books","Material")">livros</a></li>
                    <li><a href="@Url.Action("Articles","Material")">Artigos</a></li>
                    <li><a href="@Url.Action("Podcasts","Material")">Podcasts</a></li>


                    @if (Auth.IsSuccess && Auth.IsAdmin)
                    {

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Materiais
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("index","Material")">Listar</a></li>
                                <li><a href="@Url.Action("insert","Material")">Inserir</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Grupos
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("index","Group")">Listar</a></li>
                                <li><a href="@Url.Action("insert","Group")">Inserir</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Generos
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("index","Genre")">Listar</a></li>
                                <li><a href="@Url.Action("insert", "Genre")">Inserir</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Usuários
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("index","Users")">Listar</a></li>
                                <li><a href="@Url.Action("insert", "Users")">Inserir</a></li>
                            </ul>
                        </li>
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">

                    @if (SessionObj != null)
                    {
                        <li>
                            <a href="@Url.Action("logout","home")">
                                <i class="glyphicon glyphicon-log-out"></i>
                                Logout
                            </a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("cadastrar","home")">
                                <i class="glyphicon glyphicon-log-in"></i>
                                Login
                            </a>
                        </li>
                    }


                </ul>
            </div>
        </div>
    </nav>
}